Sep 05 15:11:40 ip-10-13-112-170.pwx.dev.purestorage.com portworx[1300]: time="2022-09-05T15:11:40Z" level=info msg="csi.NodePublishVolume request received. VolumeID: 920849628428829313, TargetPath: /var/lib/kubelet/pods/5a21d20f-cacd-43fe-be3e-194c34c673cd/volumes/kubernetes.io~csi/pvc-0d81053d-6952-404d-b213-2adea
82bc609/mount" component=csi-driver correlation-id=b150fe93-d7ca-4293-9e55-9bc4fef2adf3 origin=csi-driver
Sep 12 09:56:50 catl0plas14833 portworx[9180]: PXPROCS[INFO]: Started px with pid 3184
Sep 12 09:56:51 catl0plas14833 portworx[9180]: time="2022-09-12T13:56:51Z" level=error msg="failed to setup internal kvdb: failed to reinitialize internal kvdb: failed to test connection with KVDB, ensure connectivity to these endpoints [http://10.65.33.7:9019 http://10.65.33.5:9019 http://10.65.33.6:9019] is not blocked: put key: etcdserver: mvcc: database space exceeded" file="boot.go:142" component=porx/px/boot fields.func=InitAndBoot func= package=boot
Sep 27 06:08:35 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:35Z" level=info msg="Following Drive Set is attached on this node (16a99325-4507-431b-b3cc-f01f7f819f96): " file="cloud_drive.go:894" component=porx/storage/hal/provider
Sep 27 06:08:35 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:35Z" level=info msg="Bootstraping internal kvdb service." file="kvstore.go:156" component=porx/px/kvstore fn=kv-store.New id=16a99325-4507-431b-b3cc-f01f7f819f96
Sep 27 06:08:36 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:36Z" level=info msg="Mounting kvdb device /dev/nvme2n1 at /var/.px_kvdb" file="util.go:41" component=porx/px/kvstore/datadir
Sep 27 06:08:36 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:36Z" level=info msg="Setting up internal kvdb with following parameters: " file="kv_utils.go:412" component=porx/px/kvstore/utils fn=kv-utils.StartKvdb id=16a99325-4507-431b-b3cc-f01f7f819f96
Sep 27 06:08:38 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:38Z" level=info msg="initialized internal kvdb" file="boot.go:772" component=porx/px/boot fields.func=init func= package=boot
Sep 27 06:08:38 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:38Z" level=info msg="pushed config data to kvdb" file="boot.go:162" component=porx/px/boot fields.func=InitAndBoot func= package=boot
Sep 27 06:08:39 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:39Z" level=info msg="Handled update for kvdb node (16a99325-4507-431b-b3cc-f01f7f819f96)" file="kvlistener.go:348" component=porx/px/kvstore fn=kv-listener.Update id=16a99325-4507-431b-b3cc-f01f7f819f96
Sep 27 06:08:43 ip-192-168-11-60.ec2.internal portworx[4245]: time="2022-09-27T06:08:43Z" level=info msg="Starting collector watch on  at 0" file="kvdb.go:389" component=kvdb
Sep 27 03:40:34 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:34Z" level=info msg="Could not find locally attached drive set for cluster px-cluster-2d1feca1-e934-4800-a17a-5d8250cd2856: no drive sets attached to the node" file="clouddrive.go:160" component=porx/px/config/identity
Sep 27 03:40:36 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:36Z" level=warning msg="Failed to find locally attached drive set: drive set not found" file="clouddrive.go:141" component=porx/px/config/identity
Sep 27 03:40:37 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:37Z" level=warning msg="Unable to start as a storage node: Limit for maximum storage nodes (1) in the zone (us-east-1c) reached" file="cloud_drive.go:1633" component=porx/storage/hal/provider
Sep 27 03:40:38 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:38Z" level=info msg="Cloud driver provider indicated that node cannot contribute storage as: cannot create more drives as max count limit for drive sets reached.. Starting node as storage less." file="clouddrive.go:209" component=porx/px/config/identity
Sep 27 03:41:00 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:41:00Z" level=info msg="Successfully persisted Drive Set for node 7250b84e-bd3b-4a64-9b48-20b1233efaa2 with labels map[]" file="cloud_drive.go:1675" component=porx/storage/hal/provider
Sep 27 03:40:38 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:38Z" level=info msg="Bootstraping internal kvdb service." file="kvstore.go:156" component=porx/px/kvstore fn=kv-store.New id=7250b84e-bd3b-4a64-9b48-20b1233efaa2
Sep 27 03:40:58 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:58Z" level=info msg="setting up kvdbDevice " file="datadir.go:73" component=porx/px/kvstore/datadir
Sep 27 03:40:58 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:58Z" level=info msg="Kvdb rule storage-rule instructed to not proceed with provisioning: Storage less node detected. Node cannot act as a kvdb node. Waiting for other nodes to start kvdb. To start kvdb on this storage less node, label this node as a metadata node and restart Portworx." file="kvprovision.go:339" component=porx/px/kvstore fn=kvdb-provisioner.CanProvisionKvdb id=7250b84e-bd3b-4a64-9b48-20b1233efaa2
Sep 27 03:40:58 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:58Z" level=warning msg="kvdb provisioning is not allowed on this node. Not formatting kvdb disk" file="kvstore.go:262" component=porx/px/kvstore
Sep 27 16:12:09 ip-192-168-93-84.ec2.internal portworx[6902]: time="2022-09-27T16:12:09Z" level=info msg="initialized internal kvdb" file="boot.go:772" component=porx/px/boot fields.func=init func= package=boot
Sep 27 03:40:34 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:34Z" level=info msg="Could not find locally attached drive set for cluster px-cluster-2d1feca1-e934-4800-a17a-5d8250cd2856: no drive sets attached to the node" file="clouddrive.go:160" component=porx/px/config/identity
Sep 27 03:40:36 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:36Z" level=warning msg="Failed to find locally attached drive set: drive set not found" file="clouddrive.go:141" component=porx/px/config/identity
Sep 27 03:40:38 ip-192-168-85-22.ec2.internal portworx[28442]: time="2022-09-27T03:40:38Z" level=info msg="Cloud driver provider indicated that node cannot contribute storage as: cannot create more drives as max count limit for drive sets reached.. Starting node as storage less." file="clouddrive.go:209" component=porx/px/config/identity
Sep 27 06:09:15 ip-192-168-85-22.ec2.internal portworx[22149]: time="2022-09-27T06:09:15Z" level=info msg="Kvdb operating at maximum capacity. Not starting kvdb on this node." file="kvlistener.go:176" component=porx/px/kvstore fn=kv-listener.JoinComplete id=7250b84e-bd3b-4a64-9b48-20b1233efaa2
Sep 27 06:08:39 ip-192-168-85-22.ec2.internal portworx[22149]: time="2022-09-27T06:08:39Z" level=info msg="Kvdb rule storage-rule instructed to not proceed with provisioning: Storage less node detected. Node cannot act as a kvdb node. Waiting for other nodes to start kvdb. To start kvdb on this storage less node, label this node as a metadata node and restart Portworx." file="kvprovision.go:339" component=porx/px/kvstore fn=kvdb-provisioner.CanProvisionKvdb id=7250b84e-bd3b-4a64-9b48-20b1233efaa2
Sep 27 06:08:39 ip-192-168-85-22.ec2.internal portworx[22149]: time="2022-09-27T06:08:39Z" level=warning msg="kvdb provisioning is not allowed on this node. Not formatting kvdb disk" file="kvstore.go:262" component=porx/px/kvstore
Sep 27 06:08:40 ip-192-168-85-22.ec2.internal portworx[22149]: time="2022-09-27T06:08:40Z" level=info msg="Setting lock timeout to: 3m0s" file="common.go:70" component=kvdb/common
Sep 27 06:08:40 ip-192-168-85-22.ec2.internal portworx[22149]: time="2022-09-27T06:08:40Z" level=info msg="initialized internal kvdb" file="boot.go:772" component=porx/px/boot fields.func=init func= package=boot
Sep 27 06:08:40 ip-192-168-85-22.ec2.internal portworx[22149]: time="2022-09-27T06:08:40Z" level=info msg="pushed config data to kvdb" file="boot.go:162" component=porx/px/boot fields.func=InitAndBoot func= package=boot
Sep 27 03:40:30 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:30Z" level=info msg="Could not find locally attached drive set for cluster px-cluster-2d1feca1-e934-4800-a17a-5d8250cd2856: no drive sets attached to the node" file="clouddrive.go:160" component=porx/px/config/identity
Sep 27 03:40:31 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:31Z" level=warning msg="Failed to find locally attached drive set: drive set not found" file="clouddrive.go:141" component=porx/px/config/identity
Sep 27 03:40:37 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:37Z" level=info msg="Created drive vol-028b1ebe6572d7322" file="aws_storage.go:310" component=porx/storage/hal/provider/aws
Sep 27 03:40:39 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:39Z" level=info msg="Successfully created a Drive Set for node 16a99325-4507-431b-b3cc-f01f7f819f96. Attaching it..." file="cloud_drive.go:1572" component=porx/storage/hal/provider
Sep 27 03:40:42 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:42Z" level=info msg="drive is now attached" file="cloud_drive.go:2460" Drive ID=vol-028b1ebe6572d7322 Drive PX Type=data Drive Path=/dev/nvme1n1 Drive State="Pending Add" component=porx/storage/hal/provider fn=attachDriveSetWithCleanupOnError
Sep 27 03:40:42 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:42Z" level=info msg="Successfully attached the Drive Set" file="cloud_drive.go:2463" component=porx/storage/hal/provider
Sep 27 03:40:42 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:42Z" level=info msg="Successfully attached the Drive Set" file="cloud_drive.go:2463" component=porx/storage/hal/provider
Sep 27 03:40:42 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:42Z" level=info msg="Bootstraping internal kvdb service." file="kvstore.go:156" component=porx/px/kvstore fn=kv-store.New id=16a99325-4507-431b-b3cc-f01f7f819f96
Sep 27 03:40:58 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:58Z" level=info msg="setting up kvdbDevice " file="datadir.go:73" component=porx/px/kvstore/datadir
Sep 27 03:40:58 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:58Z" level=info msg="Setting lock timeout to: 3m0s" file="common.go:70" component=kvdb/common
Sep 27 03:40:58 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:58Z" level=info msg="initialized internal kvdb" file="boot.go:772" component=porx/px/boot fields.func=init func= package=boot
Sep 27 03:40:58 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:40:58Z" level=info msg="pushed config data to kvdb" file="boot.go:162" component=porx/px/boot fields.func=InitAndBoot func= package=boot
Sep 27 03:41:08 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:41:08Z" level=info msg="Updated the current set of kvdb endpoints to: [http://192.168.79.127:9019]" file="kvlistener.go:436" component=porx/px/kvstore
Sep 27 03:41:18 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:41:18Z" level=info msg="Starting collector watch on  at 0" file="kvdb.go:389" component=kvdb
Sep 27 03:41:20 ip-192-168-11-60.ec2.internal portworx[28922]: time="2022-09-27T03:41:20Z" level=info msg="Callback watchdog started" file="kvdb_updates.go:902" component=porx/storage/driver/volume