Sep 05 15:11:40 ip-10-13-112-170.pwx.dev.purestorage.com k3s[6839]: E0905 15:11:40.874574    6839 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/pxd.portworx.com^920849628428829313 podName: nodeName:}" failed. No retries permitted until 2022-09-05 15:11:41.374542752 +0000 UTC m=+4393.049619169 (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "pvc-0d81053d-6952-404d-b213-2adea82bc609" (UniqueName: "kubernetes.io/csi/pxd.portworx.com^920849628428829313") pod "vdbench-sv4-svc-57678cbc89-25pgg" (UID: "5a21d20f-cacd-43fe-be3e-194c34c673cd") : rpc error: code = Internal desc = failed  to attach volume: Put "http://10.13.114.5:9001/v1/osd-volumes/920849628428829313": dial tcp 10.13.114.5:9001: connect: connection refused
Sep 05 14:08:40 ip-10-13-112-170.pwx.dev.purestorage.com k3s[6839]: I0905 14:08:40.126274    6839 operation_generator.go:658] "MountVolume.MountDevice succeeded for volume \"pvc-251d77bd-f5ac-4c82-9aca-f767058167e4\" (UniqueName: \"kubernetes.io/csi/pxd.portworx.com^555410506377584416\") pod \"nginx-6b5d97d5cb-vfp6l\" (UID: \"6441dfed-9989-4d74-abfd-0e5d3ae66995\") device mount path \"/var/lib/kubelet/plugins/kubernetes.io/csi/pxd.portworx.com/fb7a950c5cc4988077f9656465ac58fc546cc96dd2792fedd3bbc32e0193ee19/globalmount\"" pod="nginx-sharedv4-setupteardown-0-09-05-14h07m47s/nginx-6b5d97d5cb-vfp6l"
Sep 05 14:08:40 ip-10-13-112-170.pwx.dev.purestorage.com k3s[6839]: I0905 14:08:40.022835    6839 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"pvc-251d77bd-f5ac-4c82-   9aca-f767058167e4\" (UniqueName: \"kubernetes.io/csi/pxd.portworx.com^555410506377584416\") pod \"nginx-6b5d97d5cb-vfp6l\" (UID: \"6441dfed-9989-4d74-abfd-0e5d3ae66995\") " pod="nginx-sharedv4-setupteardown-0-09-05-14h07m47s/nginx-6b5d97d5cb-vfp6l"
